version: 1.0.{build}
image: Visual Studio 2019
environment:
  APPVEYOR_RDP_PASSWORD: aaa.123
build:
  verbosity: minimal
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
